CREATE TABLE IF NOT EXISTS product (
  id SERIAL NOT NULL PRIMARY KEY,
  title TEXT,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);